global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: http://discovery-service:8761/eureka

  - job_name: 'resource-processor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'resource-processor:8083' ]
        labels:
          application: 'resource-processor'
