server:
  port: 8083
  error:
    include-message: always

spring:
  application:
    name: resource-processor

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

com:
  chachotkin:
    service:
      resource:
        name: resource-service
      song:
        name: song-service

kafka:
  retry:
    delay: 1000
    attempts: 3
  properties:
    auto.offset.reset: latest

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  retry:
    period: 10000
    max-period: 60000
    max-attempts: 3

logging:
  pattern:
    level: trace_id=%mdc{trace_id} %5p
