eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

kafka:
  group-id: resource-upload
  bootstrap-address: localhost:9093
  topic: resource-upload
