server:
  port: 8083
  error:
    include-message: always

spring:
  application:
    name: resource-processor

eureka:
  client:
    fetch-registry: true
  instance:
    prefer-ip-address: false
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

com:
  chachotkin:
    service:
      resource:
        name: resource-service
      song:
        name: song-service

kafka:
  retry:
    delay: 1000
    attempts: 3
  properties:
    auto.offset.reset: latest

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  retry:
    period: 10000
    max-period: 60000
    max-attempts: 3
