server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: song-service-ms
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoint:
    health:
      show-details: always
