spring:
  datasource:
    url: jdbc:postgresql://${STORAGE_DB_HOST}:${STORAGE_DB_PORT}/storage-service-db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

eureka:
  instance:
    hostname: ${STORAGE_SERVICE_HOST}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}