server:
  port: 9090
  error:
    include-message: always

spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resources/**
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/songs/**
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/storages/**
        - id: grafana
          uri: http://grafana:3000
          predicates:
            - Path=/grafana/**
        - id: default
          uri: forward:/errors/invalid-resource
          predicates:
            - Path=/**
      default-filters:
        - name: CircuitBreaker
          args:
            name: ResourceUnavailable
            fallback-uri: forward:/errors/resource-unavailable
eureka:
  client:
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: trace_id=%mdc{trace_id} %5p
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

